import { Outcome, Activity } from '@/types/dashboard';

// AACL Outcomes and Activities

export const aaclOutcomes: Outcome[] = [
  {
    id: 'aacl-outcome-1',
    projectId: 'aacl',
    title: 'Children with increased opportunities to access education and acquire relevant life skills and skills for work by Feb 2025',
    description: '',
    target: undefined as any, // Not specified
    current: undefined as any, // Not specified
    unit: '',
    progress: 0,
    status: 'on-track',
  },
  {
    id: 'aacl-outcome-2',
    projectId: 'aacl',
    title: 'Families and communities with strengthened capacity to care for, protect and provide the needs of their children by Feb 2025. (18,000)',
    description: '',
    target: 18000,
    current: undefined as any, // Not specified
    unit: 'families',
    progress: 0,
    status: 'on-track',
  },
];

export const aaclActivities: Activity[] = [
  // Outcome 1 Activities
  {
    id: 'aacl-activity-1.1',
    outcomeId: 'aacl-outcome-1',
    title: 'Support child right club members to participate in international children Days (DAC, World Children, labor day, World Day against trafficking in Persons, International day of the Girl Child e.t.c)',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  {
    id: 'aacl-activity-1.2',
    outcomeId: 'aacl-outcome-1',
    title: 'Support cross-learning meetings with learners biannually across schools',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  {
    id: 'aacl-activity-1.3',
    outcomeId: 'aacl-outcome-1',
    title: 'Girls immediately safeguarded (identification for girls)',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  {
    id: 'aacl-activity-1.4',
    outcomeId: 'aacl-outcome-1',
    title: 'Stipend for mentors (10 mentors)',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  {
    id: 'aacl-activity-1.5',
    outcomeId: 'aacl-outcome-1',
    title: 'Boys Immediately safeguarded (300)',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  {
    id: 'aacl-activity-1.6',
    outcomeId: 'aacl-outcome-1',
    title: 'Conduct monthly review meetings with mentors - budget one day conference',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  {
    id: 'aacl-activity-1.7',
    outcomeId: 'aacl-outcome-1',
    title: 'Support boys with scholastic materials',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  {
    id: 'aacl-activity-1.8',
    outcomeId: 'aacl-outcome-1',
    title: 'Support girls with scholastic materials',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  {
    id: 'aacl-activity-1.9',
    outcomeId: 'aacl-outcome-1',
    title: 'Case Conferencing Conducted (10)',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  // Outcome 2 Activities
  {
    id: 'aacl-activity-2.1',
    outcomeId: 'aacl-outcome-2',
    title: 'Stipend for facilitators',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  {
    id: 'aacl-activity-2.2',
    outcomeId: 'aacl-outcome-2',
    title: 'Monthly review meetings with Facilitators',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  {
    id: 'aacl-activity-2.3',
    outcomeId: 'aacl-outcome-2',
    title: 'Regular monitoring of the parenting groups',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  {
    id: 'aacl-activity-2.4',
    outcomeId: 'aacl-outcome-2',
    title: 'Start up for households (needy cases)',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  {
    id: 'aacl-activity-2.5',
    outcomeId: 'aacl-outcome-2',
    title: 'Hold feedback and learning forums for communities annually',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  {
    id: 'aacl-activity-2.6',
    outcomeId: 'aacl-outcome-2',
    title: 'Production of IEC materials',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  {
    id: 'aacl-activity-2.7',
    outcomeId: 'aacl-outcome-2',
    title: 'Media Engagement',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
  {
    id: 'aacl-activity-2.8',
    outcomeId: 'aacl-outcome-2',
    title: 'Project Closeout meetings',
    description: '',
    progress: 0,
    status: 'not-started',
    startDate: undefined as any,
    endDate: undefined as any,
    responsible: '',
  },
];

export const aaclKPIs = [
  // Outcome 1
  { outcomeId: 'aacl-outcome-1', name: 'Number of children with increased opportunities to access education', value: 500, target: 700, unit: 'children', type: 'bar' },
  { outcomeId: 'aacl-outcome-1', name: 'Number of child right club members participating in international children Days', value: 100, target: 150, unit: 'members', type: 'bar' },
  { outcomeId: 'aacl-outcome-1', name: 'Number of cross-learning meetings with learners held', value: 4, target: 6, unit: 'meetings', type: 'progress' },
  { outcomeId: 'aacl-outcome-1', name: 'Number of girls immediately safeguarded', value: 50, target: 80, unit: 'girls', type: 'progress' },
  { outcomeId: 'aacl-outcome-1', name: 'Number of boys immediately safeguarded', value: 30, target: 50, unit: 'boys', type: 'progress' },
  { outcomeId: 'aacl-outcome-1', name: 'Number of mentors supported with stipend', value: 10, target: 10, unit: 'mentors', type: 'bar' },
  { outcomeId: 'aacl-outcome-1', name: 'Number of monthly review meetings with mentors', value: 12, target: 18, unit: 'meetings', type: 'progress' },
  { outcomeId: 'aacl-outcome-1', name: 'Number of boys supported with scholastic materials', value: 100, target: 150, unit: 'boys', type: 'bar' },
  { outcomeId: 'aacl-outcome-1', name: 'Number of girls supported with scholastic materials', value: 120, target: 170, unit: 'girls', type: 'bar' },
  { outcomeId: 'aacl-outcome-1', name: 'Number of case conferences conducted', value: 10, target: 15, unit: 'conferences', type: 'progress' },
  // Outcome 2
  { outcomeId: 'aacl-outcome-2', name: 'Number of families and communities with strengthened capacity', value: 9000, target: 18000, unit: 'families', type: 'progress' },
  { outcomeId: 'aacl-outcome-2', name: 'Number of facilitators supported with stipend', value: 20, target: 25, unit: 'facilitators', type: 'bar' },
  { outcomeId: 'aacl-outcome-2', name: 'Number of monthly review meetings with facilitators', value: 12, target: 18, unit: 'meetings', type: 'progress' },
  { outcomeId: 'aacl-outcome-2', name: 'Number of parenting groups monitored regularly', value: 15, target: 20, unit: 'groups', type: 'progress' },
  { outcomeId: 'aacl-outcome-2', name: 'Number of households supported with start up', value: 30, target: 50, unit: 'households', type: 'progress' },
  { outcomeId: 'aacl-outcome-2', name: 'Number of feedback and learning forums held for communities', value: 2, target: 4, unit: 'forums', type: 'progress' },
  { outcomeId: 'aacl-outcome-2', name: 'Number of IEC materials produced', value: 500, target: 700, unit: 'materials', type: 'bar' },
  { outcomeId: 'aacl-outcome-2', name: 'Number of media engagement events held', value: 3, target: 5, unit: 'events', type: 'progress' },
  { outcomeId: 'aacl-outcome-2', name: 'Number of project closeout meetings held', value: 1, target: 2, unit: 'meetings', type: 'progress' },
]; 