import { Outcome, Activity } from '@/types/dashboard';

// Kuimarisha Outcomes and Activities

export const kuimarishaOutcomes: Outcome[] = [
  { id: 'kuimarisha-outcome-1', projectId: 'kuimarisha', title: 'Outcome 1', description: '', target: undefined as any, current: undefined as any, unit: '', progress: 0, status: 'on-track' },
  { id: 'kuimarisha-outcome-2', projectId: 'kuimarisha', title: 'Outcome 2', description: '', target: undefined as any, current: undefined as any, unit: '', progress: 0, status: 'on-track' },
  { id: 'kuimarisha-outcome-3', projectId: 'kuimarisha', title: 'Outcome 3', description: '', target: undefined as any, current: undefined as any, unit: '', progress: 0, status: 'on-track' },
  { id: 'kuimarisha-outcome-4', projectId: 'kuimarisha', title: 'Outcome 4', description: '', target: undefined as any, current: undefined as any, unit: '', progress: 0, status: 'on-track' },
  { id: 'kuimarisha-outcome-5', projectId: 'kuimarisha', title: 'Outcome 5', description: '', target: undefined as any, current: undefined as any, unit: '', progress: 0, status: 'on-track' },
  { id: 'kuimarisha-outcome-6', projectId: 'kuimarisha', title: 'Outcome 6', description: '', target: undefined as any, current: undefined as any, unit: '', progress: 0, status: 'on-track' },
  { id: 'kuimarisha-outcome-7', projectId: 'kuimarisha', title: 'Outcome 7', description: '', target: undefined as any, current: undefined as any, unit: '', progress: 0, status: 'on-track' },
];

export const kuimarishaActivities: Activity[] = [
  // Outcome 1 Activities
  { id: 'kuimarisha-activity-1.1', outcomeId: 'kuimarisha-outcome-1', title: 'Support 24 government officers (supervisors) to continue offering supportive supervision to CFs during group parenting training to adolescent parents, caregivers and male groups on GTSP.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-1.2', outcomeId: 'kuimarisha-outcome-1', title: 'Train 22 Community Facilitators under Treatment arm of study on GTSP.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-1.3', outcomeId: 'kuimarisha-outcome-1', title: 'Facilitate a refresher training to 50 CFs (under non-study) and 23 CFs (under Treatment arm) on GTSP.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-1.4', outcomeId: 'kuimarisha-outcome-1', title: 'Train & Equip 23 CFs under Control arm of Study on SILK/COFE and 23 control team on GTSP', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-1.5', outcomeId: 'kuimarisha-outcome-1', title: 'Train 95 Community facilitators on Behavioral interventions (My health My choice, BFCI, SBCS & Life skills) to deliver to Adolescent parents & support with stipend.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-1.6', outcomeId: 'kuimarisha-outcome-1', title: 'Support Graduation of 3500 adolescent parents, male partners and caregivers', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-1.7', outcomeId: 'kuimarisha-outcome-1', title: '94 Government leaders and Supervisors refreshed on GTSP and research components via round table discussions.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-1.8', outcomeId: 'kuimarisha-outcome-1', title: 'Train 3500 adolescent girls, Caregivers and Male partners on GTSP at the community level through the CFs.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-1.9', outcomeId: 'kuimarisha-outcome-1', title: 'Conduct certification on GTSP to 95 Community Facilitators.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-1.10', outcomeId: 'kuimarisha-outcome-1', title: 'Conduct monthly/quarterly reflection meetings with project participants, government stakeholders and frontline workforce/supervisors to support strengthen the project implementation.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-1.11', outcomeId: 'kuimarisha-outcome-1', title: 'Collaborate with government supervisors and leaders to conduct monthly progress review meetings to 95 CFs monthly.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-1.12', outcomeId: 'kuimarisha-outcome-1', title: 'Conduct community awareness on ECD and positive parenting via different platforms to reach 1200 caregivers.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-1.13', outcomeId: 'kuimarisha-outcome-1', title: 'Conduct home visits to 2000 adolescent parents to strengthen GTSP and identify individual needs.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-1.14', outcomeId: 'kuimarisha-outcome-1', title: 'Equip the 72 CFs with ECD materials for homebased sessions, and 72 baby minders equipped with key ECD messages to support child stimulation during parenting sessions.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-1.15', outcomeId: 'kuimarisha-outcome-1', title: '2000 adolescent parents accessing EBI via their support groups', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-1.16', outcomeId: 'kuimarisha-outcome-1', title: '3000 Children accessing stimulation activities during parenting group sessions through Baby minders.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  // Outcome 2 Activities
  { id: 'kuimarisha-activity-2.1', outcomeId: 'kuimarisha-outcome-2', title: 'Support 80 group registration of adolescent parents through social services department.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-2.2', outcomeId: 'kuimarisha-outcome-2', title: '700 adolescent parents and caregivers under control study cohort trained on SILC/COFE.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-2.3', outcomeId: 'kuimarisha-outcome-2', title: '1000 adolescent parents linked and accessing apprenticeship services in their support groups.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-2.4', outcomeId: 'kuimarisha-outcome-2', title: 'Support 1000 adolescent parents to access business start-up grants/loans via registered groups.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-2.5', outcomeId: 'kuimarisha-outcome-2', title: 'Link 200 adolescent parents to Vocational Training Support on market-driven skill development.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-2.6', outcomeId: 'kuimarisha-outcome-2', title: 'Link/refer 1000 adolescent parents and their children to services based on their individual needs as per case plans.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-2.7', outcomeId: 'kuimarisha-outcome-2', title: '500 male partners and 1000 adolescent parents actively engaged on economic strengthening activities and sport events', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-2.8', outcomeId: 'kuimarisha-outcome-2', title: 'Identify, profile and strengthen synergies with 17 development partners/agencies/service providers to enhance service linkages/referrals to adolescent parents as per case plans.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-2.9', outcomeId: 'kuimarisha-outcome-2', title: 'Support 2000 children to adolescent girls with snacks (uji) and ensure access to child friendly play materials & mats.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-2.10', outcomeId: 'kuimarisha-outcome-2', title: '2000 Adolescent parents (Girls) have access to dignity packs', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-2.11', outcomeId: 'kuimarisha-outcome-2', title: 'Support adolescent parents to access civil registration services (IDs/ and Birth certificates)', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-2.12', outcomeId: 'kuimarisha-outcome-2', title: 'Support 100 PWDs - children/adolescent parents to access services based on needs (assessment/reviews).', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  // Outcome 3 Activities
  { id: 'kuimarisha-activity-3.1', outcomeId: 'kuimarisha-outcome-3', title: 'Provide teaching/training aids and M&E tools to 95 Community Facilitators to deliver GTSP sessions and home visits.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-3.2', outcomeId: 'kuimarisha-outcome-3', title: 'Support 80 community leaders (chiefs/Ass.chiefs,CAA, -ward admins) to conduct community dialogues and sensitization forums on ECD and Positive parenting practices.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-3.3', outcomeId: 'kuimarisha-outcome-3', title: 'Support in securing safe venues for Adolescent Parents group sessions', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-3.4', outcomeId: 'kuimarisha-outcome-3', title: 'Conduct 2 County dialogues in collaboration with URAIA.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-3.5', outcomeId: 'kuimarisha-outcome-3', title: 'Conduct community entry in new sub-locations with leaders.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  // Outcome 4 Activities
  { id: 'kuimarisha-activity-4.1', outcomeId: 'kuimarisha-outcome-4', title: 'Conduct dialogue forums with 30 cultural leaders/elders/Ritual leaders (\'ABASAMI\') and religious leaders to prevent/end teen pregnancies.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-4.2', outcomeId: 'kuimarisha-outcome-4', title: 'Identify and conduct 4 community campaigns through theatre teams (Edutainment) to highlight importance of male engagement in parenting and prevention of teen pregnancies/child marriages.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-4.3', outcomeId: 'kuimarisha-outcome-4', title: 'Celebration of International days(DAC/Day of the girl child/IDOF etc)', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  // Outcome 5 Activities
  { id: 'kuimarisha-activity-5.1', outcomeId: 'kuimarisha-outcome-5', title: 'Evaluate effects & cost-costeffectiveness of delivering GTSP via government workforce.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-5.2', outcomeId: 'kuimarisha-outcome-5', title: 'Hold radio talk shows/bulletins, twitter space, stakeholder physical meetings, media engagement & webinars to disseminate findings/learnings on the effects & costs of delivering GTSP.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-5.3', outcomeId: 'kuimarisha-outcome-5', title: 'Jointly develop learning briefs/ Fact sheets/Impact evaluation paper/policy paper briefs/white papers/working papers/full reports to share impact/preliminary findings on research.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-5.4', outcomeId: 'kuimarisha-outcome-5', title: 'Hold round-table discussions with policymakers/county legislative (County assembly committee chairpersons on ECD, Budgets & Social) to influence uptake of evidence-based GTSP & ECD for county planning/budgeting at scale.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-5.5', outcomeId: 'kuimarisha-outcome-5', title: 'Support & technically participate in (TWGs, MST/Child Advisory Committee, Policy networks, ECDNetwork forums, cross sector forums and  Conferences) & disseminate findings/lessons (Regional, National and County).', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-5.6', outcomeId: 'kuimarisha-outcome-5', title: 'Work jointly with the government to strengthen/development of cross-sectoral standards and referrals', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-5.7', outcomeId: 'kuimarisha-outcome-5', title: 'Conduct/support 4 review meetings with county and sub-county teams to update government on progress of GTSP/PROJECT and aligning project priorities with County priorities.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-5.8', outcomeId: 'kuimarisha-outcome-5', title: 'Support government to disseminate/develop and contextualize 1 important ECD (parenting highlights) policy.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-5.9', outcomeId: 'kuimarisha-outcome-5', title: 'Document learning case studies to inform GTSP efforts on early childhood development and caregiver wellbeing and dissemination of research findings through journals.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-5.10', outcomeId: 'kuimarisha-outcome-5', title: 'Analyze service/system gaps and Support/conduct capacity development meetings with government service providers (jointly)', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-5.11', outcomeId: 'kuimarisha-outcome-5', title: 'Support Nurturing care Cross-sector review meetings/trainings to strengthen service delivery.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-5.12', outcomeId: 'kuimarisha-outcome-5', title: 'Conduct Joint stakeholder planning meetings biannual 35 pax * 2 days at county/national to support ECD/Parenting policy/legal framework/lobby.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-5.13', outcomeId: 'kuimarisha-outcome-5', title: 'Advocate and ensure support for Early learning labs/hubs (locally resourced) in designated Community safe space to enhance child stimulation.', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  // Outcome 6 Activities
  { id: 'kuimarisha-activity-6.1', outcomeId: 'kuimarisha-outcome-6', title: 'Integrated community outreach: Comprehensively addressing gaps, and convenient servicing in supportive settings which promote utilization of services', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-6.2', outcomeId: 'kuimarisha-outcome-6', title: 'Support and participate in County/community leaders planning meeting', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  // Outcome 7 Activities
  { id: 'kuimarisha-activity-7.1', outcomeId: 'kuimarisha-outcome-7', title: 'Staff capacity strengthening and development on climate change, ECD gender mainstreaming & Parenting programming', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-7.2', outcomeId: 'kuimarisha-outcome-7', title: 'Enhance digitization of reports and monitoring tools to increase efficiency (Data management system)', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-7.3', outcomeId: 'kuimarisha-outcome-7', title: 'Conduct Outcome harvesting, Data entries/verifications and Support  M& E field visits (midlines and endlines).', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-7.4', outcomeId: 'kuimarisha-outcome-7', title: 'Support HOCAI, (Holistic Organization Capacity Assessment Instruments)', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-7.5', outcomeId: 'kuimarisha-outcome-7', title: 'Support internal project management technical review and co-refining of project with stakeholders', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
  { id: 'kuimarisha-activity-7.6', outcomeId: 'kuimarisha-outcome-7', title: 'Develop and design IEC materials to support project visibility/ branding and increase learning for young children', description: '', progress: 0, status: 'not-started', startDate: undefined as any, endDate: undefined as any, responsible: '' },
];

export const kuimarishaKPIs = [
  // Outcome 1
  { outcomeId: 'kuimarisha-outcome-1', name: 'Number of government officers (supervisors) offering supportive supervision', value: 24, target: 30, unit: 'officers', type: 'bar' },
  { outcomeId: 'kuimarisha-outcome-1', name: 'Number of Community Facilitators trained on GTSP', value: 22, target: 30, unit: 'facilitators', type: 'bar' },
  { outcomeId: 'kuimarisha-outcome-1', name: 'Number of adolescent parents, male partners and caregivers graduated', value: 3500, target: 4000, unit: 'graduates', type: 'progress' },
  { outcomeId: 'kuimarisha-outcome-1', name: 'Number of home visits to adolescent parents', value: 2000, target: 2500, unit: 'visits', type: 'progress' },
  { outcomeId: 'kuimarisha-outcome-1', name: 'Number of children accessing stimulation activities during parenting group sessions', value: 3000, target: 3500, unit: 'children', type: 'bar' },
  // Outcome 2
  { outcomeId: 'kuimarisha-outcome-2', name: 'Number of adolescent parents trained on SILC/COFE', value: 700, target: 800, unit: 'parents', type: 'bar' },
  { outcomeId: 'kuimarisha-outcome-2', name: 'Number of adolescent parents linked to apprenticeship services', value: 1000, target: 1200, unit: 'parents', type: 'bar' },
  { outcomeId: 'kuimarisha-outcome-2', name: 'Number of adolescent parents accessing business start-up grants/loans', value: 1000, target: 1200, unit: 'parents', type: 'bar' },
  { outcomeId: 'kuimarisha-outcome-2', name: 'Number of children supported with snacks and play materials', value: 2000, target: 2200, unit: 'children', type: 'bar' },
  // Outcome 3
  { outcomeId: 'kuimarisha-outcome-3', name: 'Number of community leaders conducting dialogues and sensitization forums', value: 80, target: 100, unit: 'leaders', type: 'bar' },
  { outcomeId: 'kuimarisha-outcome-3', name: 'Number of safe venues secured for group sessions', value: 10, target: 15, unit: 'venues', type: 'progress' },
  // Outcome 4
  { outcomeId: 'kuimarisha-outcome-4', name: 'Number of dialogue forums with cultural and religious leaders', value: 30, target: 40, unit: 'forums', type: 'progress' },
  { outcomeId: 'kuimarisha-outcome-4', name: 'Number of community campaigns through theatre teams', value: 4, target: 6, unit: 'campaigns', type: 'progress' },
  // Outcome 5
  { outcomeId: 'kuimarisha-outcome-5', name: 'Number of radio talk shows/bulletins/webinars held', value: 5, target: 8, unit: 'events', type: 'progress' },
  { outcomeId: 'kuimarisha-outcome-5', name: 'Number of learning briefs/fact sheets/reports developed', value: 3, target: 5, unit: 'briefs', type: 'progress' },
  // Outcome 6
  { outcomeId: 'kuimarisha-outcome-6', name: 'Number of integrated community outreach events held', value: 10, target: 15, unit: 'events', type: 'progress' },
  // Outcome 7
  { outcomeId: 'kuimarisha-outcome-7', name: 'Number of staff trained on climate change, ECD gender mainstreaming & Parenting programming', value: 20, target: 30, unit: 'staff', type: 'bar' },
  { outcomeId: 'kuimarisha-outcome-7', name: 'Number of digitized reports and monitoring tools', value: 5, target: 10, unit: 'tools', type: 'progress' },
]; 