import { Outcome, Activity, SubActivity as BaseSubActivity } from '@/types/dashboard';

export interface Output {
  id: string;
  title: string;
  description: string;
  target: number;
  current: number;
  unit: string;
  status: 'on-track' | 'at-risk' | 'behind' | 'completed';
  outcomeId: string;
  activities: string[];
  projectId: string;
}

// Locally extend SubActivity to include parentId for filtering
interface SubActivity extends BaseSubActivity {
  parentId: string;
}

// Internal array with parentId for filtering
const mamebSubActivitiesWithParentId: SubActivity[] = [
  // Outcome 1
  { id: '1.1.1', parentId: 'activity-1.1', title: 'Mentor recruitment and selection', description: 'Identify and recruit suitable mentors from each school', status: 'completed', progress: 100, dueDate: '2023-02-28' },
  { id: '1.1.2', parentId: 'activity-1.1', title: 'Mentor training workshops', description: 'Conduct comprehensive training workshops for selected mentors', status: 'in-progress', progress: 80, dueDate: '2023-08-31' },
  { id: '1.1.3', parentId: 'activity-1.1', title: 'Mentor certification and ongoing support', description: 'Certify trained mentors and provide ongoing support', status: 'not-started', progress: 20, dueDate: '2023-12-31' },
  { id: '1.2.1', parentId: 'activity-1.2', title: 'Club formation and registration', description: 'Form and register new child clubs in target areas', status: 'completed', progress: 100, dueDate: '2023-04-30' },
  { id: '1.2.2', parentId: 'activity-1.2', title: 'Club leadership training', description: 'Train club leaders and provide governance support', status: 'in-progress', progress: 70, dueDate: '2023-09-30' },
  { id: '1.2.3', parentId: 'activity-1.2', title: 'Club activity implementation', description: 'Support clubs in implementing their activity plans', status: 'in-progress', progress: 60, dueDate: '2023-11-30' },
  { id: '1.3.1', parentId: 'activity-1.3', title: 'Sensitize schools on the use of speak out boxes', description: 'Conduct sensitization sessions with school administrators and teachers', status: 'completed', progress: 100, dueDate: '2023-04-30' },
  { id: '1.3.2', parentId: 'activity-1.3', title: 'Provide talking walls and speak out boxes in schools', description: 'Install talking walls and speak out boxes in all 5 target schools', status: 'in-progress', progress: 60, dueDate: '2023-09-30' },
  { id: '1.3.3', parentId: 'activity-1.3', title: 'Facilitate referral and response to children - Case management', description: 'Establish case management system for reports received through mechanisms', status: 'in-progress', progress: 40, dueDate: '2023-11-30' },
  { id: '1.4.1', parentId: 'activity-1.4', title: 'Curriculum development', description: 'Develop age-appropriate life skills curriculum', status: 'completed', progress: 100, dueDate: '2023-03-31' },
  { id: '1.4.2', parentId: 'activity-1.4', title: 'Teacher training', description: 'Train teachers on life skills education delivery', status: 'completed', progress: 100, dueDate: '2023-05-31' },
  { id: '1.4.3', parentId: 'activity-1.4', title: 'Program implementation', description: 'Roll out life skills education programs', status: 'in-progress', progress: 45, dueDate: '2023-12-31' },
  { id: '1.5.1', parentId: 'activity-1.5', title: 'Child participation training', description: 'Train children on meaningful participation principles', status: 'in-progress', progress: 60, dueDate: '2023-08-31' },
  { id: '1.5.2', parentId: 'activity-1.5', title: 'Establish child parliaments', description: 'Establish child parliaments in schools and communities', status: 'in-progress', progress: 40, dueDate: '2023-10-31' },
  { id: '1.5.3', parentId: 'activity-1.5', title: 'Youth advocacy campaigns', description: 'Support youth-led advocacy campaigns', status: 'not-started', progress: 20, dueDate: '2023-12-31' },
  { id: '1.6.1', parentId: 'activity-1.6', title: 'Campaign material development', description: 'Develop age-appropriate campaign materials', status: 'completed', progress: 100, dueDate: '2023-04-30' },
  { id: '1.6.2', parentId: 'activity-1.6', title: 'School-based campaigns', description: 'Conduct rights awareness campaigns in schools', status: 'in-progress', progress: 70, dueDate: '2023-09-30' },
  { id: '1.6.3', parentId: 'activity-1.6', title: 'Community outreach', description: 'Conduct community-based awareness activities', status: 'in-progress', progress: 65, dueDate: '2023-11-30' },
  // Outcome 2
  { id: '2.1.1', parentId: 'activity-2.1', title: 'Develop parenting training curriculum', description: 'Create comprehensive curriculum for skilful parenting training', status: 'completed', progress: 100, dueDate: '2023-03-31' },
  { id: '2.1.2', parentId: 'activity-2.1', title: 'Conduct parenting training sessions', description: 'Deliver training sessions to groups of parents', status: 'in-progress', progress: 72, dueDate: '2023-12-31' },
  { id: '2.1.3', parentId: 'activity-2.1', title: 'Follow-up and support sessions', description: 'Provide ongoing support and follow-up to trained parents', status: 'in-progress', progress: 30, dueDate: '2023-12-31' },
  // Outcome 3
  { id: '3.1.1', parentId: 'activity-3.1', title: 'Leader identification and recruitment', description: 'Identify and recruit influential community and religious leaders', status: 'completed', progress: 100, dueDate: '2023-03-31' },
  { id: '3.1.2', parentId: 'activity-3.1', title: 'Leadership training workshops', description: 'Conduct comprehensive training workshops for leaders', status: 'in-progress', progress: 75, dueDate: '2023-09-30' },
  { id: '3.1.3', parentId: 'activity-3.1', title: 'Community mobilization activities', description: 'Support leaders in conducting community mobilization', status: 'in-progress', progress: 65, dueDate: '2023-12-31' },
  // Outcome 4
  { id: '4.1.1', parentId: 'activity-4.1', title: 'School assessment and planning', description: 'Conduct comprehensive assessments and develop improvement plans', status: 'completed', progress: 100, dueDate: '2023-04-30' },
  { id: '4.1.2', parentId: 'activity-4.1', title: 'Teacher training and capacity building', description: 'Train teachers on child protection and positive discipline', status: 'in-progress', progress: 60, dueDate: '2023-10-31' },
  { id: '4.1.3', parentId: 'activity-4.1', title: 'Resource development and provision', description: 'Develop and provide necessary resources for schools', status: 'in-progress', progress: 45, dueDate: '2023-12-31' },
  // Outcome 5
  { id: '5.1.1', parentId: 'activity-5.1', title: 'Stakeholder mapping and engagement', description: 'Map key stakeholders and initiate engagement processes', status: 'completed', progress: 100, dueDate: '2023-03-31' },
  { id: '5.1.2', parentId: 'activity-5.1', title: 'Partnership agreement development', description: 'Develop formal partnership agreements', status: 'in-progress', progress: 60, dueDate: '2023-09-30' },
  { id: '5.1.3', parentId: 'activity-5.1', title: 'Joint program implementation', description: 'Implement joint programs and activities', status: 'in-progress', progress: 40, dueDate: '2023-12-31' },
];

// Export subActivities without parentId for external use
export const mamebSubActivities: BaseSubActivity[] = mamebSubActivitiesWithParentId.map(({ parentId, ...rest }) => rest);

export const mamebOutcomes: Outcome[] = [
  {
    id: 'outcome-1',
    projectId: 'mameb',
    title: "Children's Rights and Empowerment",
    description: "3000 children have knowledge on their rights, and skills to make informed decisions and meaningfully engage with other actors for their own education success, safety and wellbeing by 2027",
    target: 3000,
    current: 1350,
    unit: 'children',
    progress: 45,
    status: 'on-track',
  },
  {
    id: 'outcome-2',
    projectId: 'mameb',
    title: 'Enhanced Parent-Teacher-Learner Collaboration',
    description: 'Enhanced collaboration between parents, teachers and learners resulting in improved learning and protection outcomes',
    target: 100,
    current: 68,
    unit: '% improvement',
    progress: 68,
    status: 'on-track',
  },
  {
    id: 'outcome-3',
    projectId: 'mameb',
    title: 'Community and Religious Leaders Engagement',
    description: '100 community and religious leaders model and promote the right to learning and protection and take action to coordinate efforts towards the realization of child rights at all levels',
    target: 100,
    current: 72,
    unit: 'leaders',
    progress: 72,
    status: 'on-track',
  },
  {
    id: 'outcome-4',
    projectId: 'mameb',
    title: 'School Capacity and Resources',
    description: 'Schools have the right capacity, resources, and policies and are implementing actions in collaboration with education stakeholders towards better safety and learning outcomes for children',
    target: 5,
    current: 3,
    unit: 'schools',
    progress: 60,
    status: 'on-track',
  },
  {
    id: 'outcome-5',
    projectId: 'mameb',
    title: 'Government and CSO Collaboration',
    description: 
      "Collaborate with Government and CSOs in conducting stakeholders' engagement meetings to raise awareness on children rights and the importance for their protection and well-being",
    target: 12,
    current: 7,
    unit: 'meetings',
    progress: 58,
    status: 'on-track',
  },
];

export const mamebOutputs: Output[] = [
  // Outcome 1 Outputs
  {
    id: '1.1',
    title: 'Children who report improved knowledge on their rights',
    description: 'Percentage of children demonstrating improved understanding of their rights and responsibilities through assessments and surveys.',
    target: 80,
    current: 65,
    unit: '%',
    status: 'on-track',
    outcomeId: '1',
    activities: ['1.1', '1.2'],
    projectId: 'mameb',
  },
  {
    id: '1.2',
    title: 'Children actively using safe platforms to engage on their rights',
    description: 'Percentage of children utilizing designated safe platforms and mechanisms for expressing their views and concerns.',
    target: 70,
    current: 45,
    unit: '%',
    status: 'at-risk',
    outcomeId: '1',
    activities: ['1.2', '1.5'],
    projectId: 'mameb',
  },
  {
    id: '1.3',
    title: 'Mentors trained on life skills value-based education',
    description: 'Number of mentors successfully trained and certified in life skills value-based education methodologies.',
    target: 5,
    current: 4,
    unit: 'mentors',
    status: 'on-track',
    outcomeId: '1',
    activities: ['1.1'],
    projectId: 'mameb',
  },
  {
    id: '1.4',
    title: 'Children participating in life skills education',
    description: 'Number of children actively participating in life skills education programs.',
    target: 3000,
    current: 1350,
    unit: 'children',
    status: 'on-track',
    outcomeId: '1',
    activities: ['1.1', '1.4'],
    projectId: 'mameb',
  },
  {
    id: '1.5',
    title: 'Clubs created or strengthened',
    description: 'Number of child rights clubs that have been established or strengthened.',
    target: 10,
    current: 7,
    unit: 'clubs',
    status: 'on-track',
    outcomeId: '1',
    activities: ['1.2'],
    projectId: 'mameb',
  },
  {
    id: '1.6',
    title: 'Children in club activities',
    description: 'Number of children actively participating in club activities.',
    target: 2500,
    current: 980,
    unit: 'children',
    status: 'behind',
    outcomeId: '1',
    activities: ['1.2', '1.5'],
    projectId: 'mameb',
  },
  {
    id: '1.7',
    title: 'Learners sensitized on speak out boxes',
    description: 'Number of learners who have been sensitized on the use of speak out boxes.',
    target: 3000,
    current: 2100,
    unit: 'learners',
    status: 'on-track',
    outcomeId: '1',
    activities: ['1.3'],
    projectId: 'mameb',
  },
  {
    id: '1.8',
    title: 'Using child-friendly reporting mechanisms',
    description: 'Percentage of children using child-friendly reporting mechanisms.',
    target: 60,
    current: 42,
    unit: '%',
    status: 'on-track',
    outcomeId: '1',
    activities: ['1.3'],
    projectId: 'mameb',
  },
  {
    id: '1.9',
    title: 'Incidents reported through speak out boxes',
    description: 'Number of incidents reported through speak out boxes.',
    target: 50,
    current: 23,
    unit: 'incidents',
    status: 'at-risk',
    outcomeId: '1',
    activities: ['1.3'],
    projectId: 'mameb',
  },
  // Outcome 2 Outputs
  {
    id: '2.1',
    title: 'Parents trained and graduated from Skilful parenting training',
    description: 'Number of parents who have successfully completed the comprehensive skilful parenting training program.',
    target: 200,
    current: 145,
    unit: 'parents',
    status: 'on-track',
    outcomeId: '2',
    activities: ['2.1'],
    projectId: 'mameb',
  },
  {
    id: '2.2',
    title: 'Parents demonstrating improved parenting skills',
    description: 'Percentage of parents demonstrating improved parenting skills through assessments.',
    target: 85,
    current: 72,
    unit: '%',
    status: 'on-track',
    outcomeId: '2',
    activities: ['2.1'],
    projectId: 'mameb',
  },
  {
    id: '2.3',
    title: 'Parent-teacher meetings held regularly',
    description: 'Number of schools where parent-teacher meetings are held regularly.',
    target: 5,
    current: 4,
    unit: 'schools',
    status: 'on-track',
    outcomeId: '2',
    activities: ['2.1'],
    projectId: 'mameb',
  },
  {
    id: '2.4',
    title: 'Parents actively involved in school activities',
    description: 'Percentage of parents actively involved in school activities.',
    target: 70,
    current: 58,
    unit: '%',
    status: 'at-risk',
    outcomeId: '2',
    activities: ['2.1'],
    projectId: 'mameb',
  },
  {
    id: '2.5',
    title: 'Positive parenting practices reported',
    description: 'Percentage of parents reporting use of positive parenting practices.',
    target: 80,
    current: 67,
    unit: '%',
    status: 'on-track',
    outcomeId: '2',
    activities: ['2.1'],
    projectId: 'mameb',
  },
  // Outcome 3 Outputs
  {
    id: '3.1',
    title: 'Parents reporting positive influence from community and religious leaders',
    description: 'Proportion of parents who report positive influence and support from trained community and religious leaders.',
    target: 85,
    current: 67,
    unit: '%',
    status: 'on-track',
    outcomeId: '3',
    activities: ['3.1'],
    projectId: 'mameb',
  },
  {
    id: '3.2',
    title: 'Community leaders actively promoting child protection',
    description: 'Number of community leaders actively promoting child protection practices.',
    target: 20,
    current: 15,
    unit: 'leaders',
    status: 'on-track',
    outcomeId: '3',
    activities: ['3.1'],
    projectId: 'mameb',
  },
  {
    id: '3.3',
    title: 'Community awareness sessions conducted',
    description: 'Number of community awareness sessions conducted by trained leaders.',
    target: 50,
    current: 32,
    unit: 'sessions',
    status: 'on-track',
    outcomeId: '3',
    activities: ['3.1'],
    projectId: 'mameb',
  },
  {
    id: '3.4',
    title: 'Community members reached through awareness campaigns',
    description: 'Number of community members reached through awareness campaigns.',
    target: 2000,
    current: 1280,
    unit: 'people',
    status: 'on-track',
    outcomeId: '3',
    activities: ['3.1'],
    projectId: 'mameb',
  },
  // Outcome 4 Outputs
  {
    id: '4.1',
    title: 'Schools with improved child protection policies',
    description: 'Number of schools with improved and implemented child protection policies.',
    target: 5,
    current: 3,
    unit: 'schools',
    status: 'at-risk',
    outcomeId: '4',
    activities: ['4.1'],
    projectId: 'mameb',
  },
  {
    id: '4.2',
    title: 'Teachers trained on child protection',
    description: 'Number of teachers trained on child protection and positive discipline.',
    target: 50,
    current: 28,
    unit: 'teachers',
    status: 'behind',
    outcomeId: '4',
    activities: ['4.1'],
    projectId: 'mameb',
  },
  // Outcome 5 Outputs
  {
    id: '5.1',
    title: 'Government-CSO partnerships established',
    description: 'Number of formal partnerships established between government agencies and CSOs.',
    target: 10,
    current: 6,
    unit: 'partnerships',
    status: 'on-track',
    outcomeId: '5',
    activities: ['5.1'],
    projectId: 'mameb',
  },
];

export const mamebKPIs = [
  // Outcome 1
  { outcomeId: 'outcome-1', name: '% of children who report improved knowledge on their rights and responsibilities', value: 78, target: 90, unit: '%', type: 'radialGauge' },
  { outcomeId: 'outcome-1', name: '% of children actively using safe platforms to engage on their rights', value: 62, target: 80, unit: '%', type: 'radialGauge' },
  { outcomeId: 'outcome-1', name: '# of mentors trained on life skills value-based education', value: 14, target: 20, unit: 'mentors', type: 'bar' },
  { outcomeId: 'outcome-1', name: '# of children participating in life skills value-based education', value: 1200, target: 2000, unit: 'children', type: 'bar' },
  { outcomeId: 'outcome-1', name: '# of clubs created or strengthened', value: 8, target: 10, unit: 'clubs', type: 'progress' },
  { outcomeId: 'outcome-1', name: '# of children actively participating in club activities', value: 950, target: 1500, unit: 'children', type: 'bar' },
  { outcomeId: 'outcome-1', name: '# of learners sensitized on speak out boxes', value: 2100, target: 3000, unit: 'learners', type: 'bar' },
  { outcomeId: 'outcome-1', name: '% of learners utilizing child-friendly reporting mechanisms', value: 42, target: 60, unit: '%', type: 'radialGauge' },
  { outcomeId: 'outcome-1', name: '# of incidences reported through speak out boxes', value: 23, target: 50, unit: 'incidents', type: 'bar' },
  // Outcome 2
  { outcomeId: 'outcome-2', name: '# Parents trained and graduated from Skilful parenting training', value: 320, target: 500, unit: 'parents', type: 'bar' },
  { outcomeId: 'outcome-2', name: '% of parents/caregivers with improved knowledge on positive parenting', value: 68, target: 85, unit: '%', type: 'radialGauge' },
  { outcomeId: 'outcome-2', name: '# of collaborative initiatives launched by parents, caregivers, and teachers', value: 12, target: 20, unit: 'initiatives', type: 'progress' },
  { outcomeId: 'outcome-2', name: '# of community awareness sessions held', value: 18, target: 30, unit: 'sessions', type: 'bar' },
  // Outcome 3
  { outcomeId: 'outcome-3', name: 'Proportion of parents reporting positive influence from community and religious leaders', value: 67, target: 85, unit: '%', type: 'radialGauge' },
  { outcomeId: 'outcome-3', name: '# of community and religious leaders trained', value: 45, target: 60, unit: 'leaders', type: 'bar' },
  { outcomeId: 'outcome-3', name: '# parents reached through community awareness', value: 1200, target: 2000, unit: 'parents', type: 'bar' },
  // Outcome 4
  { outcomeId: 'outcome-4', name: '# club patrons trained', value: 10, target: 15, unit: 'patrons', type: 'progress' },
  { outcomeId: 'outcome-4', name: '# of teachers and staff trained on child protection', value: 32, target: 50, unit: 'staff', type: 'bar' },
  // Outcome 5
  { outcomeId: 'outcome-5', name: '# of stakeholder review meetings conducted', value: 7, target: 12, unit: 'meetings', type: 'progress' },
];

export const mamebActivities: Activity[] = [
  // Outcome 1 Activities
  {
    id: 'activity-1.1',
    outcomeId: 'outcome-1',
    title: 'Recruitment and training of mentors',
    description: 'Recruit and train 5 mentors (1 per school) with refreshments and transport reimbursement',
    progress: 80,
    status: 'in-progress',
    startDate: new Date('2023-02-01'),
    endDate: new Date('2024-01-31'),
    responsible: 'Mary Wanjiku',
    subActivities: mamebSubActivitiesWithParentId.filter(sa => sa.parentId === 'activity-1.1').map(({parentId, ...rest}) => rest),
  },
  {
    id: 'activity-1.2',
    outcomeId: 'outcome-1',
    title: 'Formation of child rights clubs',
    description: 'Form child rights clubs where children meet to express opinions, discuss rights and plan advocacy (two clubs per school in 5 schools)',
    progress: 70,
    status: 'in-progress',
    startDate: new Date('2023-03-01'),
    endDate: new Date('2024-02-28'),
    responsible: 'John Kimani',
    subActivities: mamebSubActivitiesWithParentId.filter(sa => sa.parentId === 'activity-1.2').map(({parentId, ...rest}) => rest),
  },
  {
    id: 'activity-1.3',
    outcomeId: 'outcome-1',
    title: 'Establish child friendly reporting mechanisms',
    description: 'Establish child friendly reporting mechanisms within schools and communities that encourage children to report violence and seek support',
    progress: 85,
    status: 'in-progress',
    startDate: new Date('2023-01-15'),
    endDate: new Date('2023-12-31'),
    responsible: 'Grace Muthoni',
    subActivities: mamebSubActivitiesWithParentId.filter(sa => sa.parentId === 'activity-1.3').map(({parentId, ...rest}) => rest),
  },
  {
    id: 'activity-1.4',
    outcomeId: 'outcome-1',
    title: 'Child-friendly key messages creation',
    description: 'Engage children in creating child friendly key messages through artwork, illustrations, storytelling, writings, and songs',
    progress: 60,
    status: 'in-progress',
    startDate: new Date('2023-04-01'),
    endDate: new Date('2024-03-31'),
    responsible: 'Peter Ochieng',
    subActivities: mamebSubActivitiesWithParentId.filter(sa => sa.parentId === 'activity-1.4').map(({parentId, ...rest}) => rest),
  },
  {
    id: 'activity-1.5',
    outcomeId: 'outcome-1',
    title: "Children's participation in assemblies and events",
    description: "Facilitate learners to participate in children's assemblies, summits, inter-school debates, and cultural days",
    progress: 45,
    status: 'in-progress',
    startDate: new Date('2023-05-01'),
    endDate: new Date('2024-04-30'),
    responsible: 'Anne Njeri',
    subActivities: mamebSubActivitiesWithParentId.filter(sa => sa.parentId === 'activity-1.5').map(({parentId, ...rest}) => rest),
  },
  {
    id: 'activity-1.6',
    outcomeId: 'outcome-1',
    title: 'Media campaigns for children',
    description: 'Conduct media campaigns for children to express their views and raise awareness',
    progress: 30,
    status: 'in-progress',
    startDate: new Date('2023-06-01'),
    endDate: new Date('2024-05-31'),
    responsible: 'David Mutua',
    subActivities: mamebSubActivitiesWithParentId.filter(sa => sa.parentId === 'activity-1.6').map(({parentId, ...rest}) => rest),
  },
  // Outcome 2 Activities
  {
    id: 'activity-2.1',
    outcomeId: 'outcome-2',
    title: 'Skillful parenting training',
    description: 'Train parents and caregivers on positive parenting skills and child development',
    progress: 75,
    status: 'in-progress',
    startDate: new Date('2023-03-01'),
    endDate: new Date('2024-02-29'),
    responsible: 'Susan Wanjiru',
    subActivities: mamebSubActivitiesWithParentId.filter(sa => sa.parentId === 'activity-2.1').map(({parentId, ...rest}) => rest),
  },
  {
    id: 'activity-2.2',
    outcomeId: 'outcome-2',
    title: 'Parent-teacher collaboration initiatives',
    description: 'Launch collaborative initiatives between parents, caregivers, and teachers for safe learning environments',
    progress: 55,
    status: 'in-progress',
    startDate: new Date('2023-04-01'),
    endDate: new Date('2024-03-31'),
    responsible: 'James Kariuki',
    subActivities: mamebSubActivitiesWithParentId.filter(sa => sa.parentId === 'activity-2.2').map(({parentId, ...rest}) => rest),
  },
  // Outcome 3 Activities
  {
    id: 'activity-3.1',
    outcomeId: 'outcome-3',
    title: 'Community leaders mapping and training',
    description: 'Identify, map and train community and religious leaders on child rights and their roles as duty bearers',
    progress: 80,
    status: 'in-progress',
    startDate: new Date('2023-02-01'),
    endDate: new Date('2024-01-31'),
    responsible: 'Pastor Michael Omondi',
    subActivities: mamebSubActivitiesWithParentId.filter(sa => sa.parentId === 'activity-3.1').map(({parentId, ...rest}) => rest),
  },
  {
    id: 'activity-3.2',
    outcomeId: 'outcome-3',
    title: 'Community awareness sessions',
    description: 'Conduct community awareness sessions led by trained religious and community leaders',
    progress: 65,
    status: 'in-progress',
    startDate: new Date('2023-05-01'),
    endDate: new Date('2024-04-30'),
    responsible: 'Elder Sarah Akinyi',
    subActivities: mamebSubActivitiesWithParentId.filter(sa => sa.parentId === 'activity-3.2').map(({parentId, ...rest}) => rest),
  },
]; 